#!/bin/bash

#Philipp "3D" ten Brink
#2018-01-04
#donations: VRM/VRC VJniF5bP9Acy7ce33yR4jRYSQ66Z4vGH8s

#GNU General Public License v3.0 see LICENSE

if [ "$(id -u)" != "0" ]; then
	echo "Sorry, you are not root or sudo."
	exit 1
fi

type=$(lscpu | grep -m 1 "Architecture:" | sed 's/[^=:]*[=:] //' | sed 's|[/ ]||g')

benchmark () { 

	if [ $(ls /dev/mem | grep -c /) -gt 0 ]; then 
		ram_type=$(dmidecode -t 17 | grep -m 1 "Type:" | sed 's/[^=:]*[=:] //')
		ram_speed=$(dmidecode -t 17 | grep -m 1 "Speed:" | sed 's/[^=:]*[=:] //' | tr -d '[:alpha:]' | sed 's|[/, ]||g')
	else
		ram_type="no /dev/mem folder - sbc or docker"
		ram_speed=0
	fi
	
	proc=$(cat /proc/cpuinfo | grep -m 1 "model name" | sed 's/[^=:]*[=:] //' | sed 's/[@].*$//')
	proc_frq=$(cat /proc/cpuinfo | grep -m 1 "model name" | sed 's/[^=:]*[=:] //' | sed 's/[^@]*@ //' | tr -d '[:alpha:]')
	ram_amount_kb=$(cat /proc/meminfo | grep -m 1 "MemTotal:" | sed 's/[^=:]*[=:] //' | tr -d '[:alpha:]' | sed 's|[/ ]||g')
	ram_amount_mb=$((ram_amount_kb/1000))
	os=$(lsb_release -d -s)
	kernel=$(uname -r)
	proc_type=$(lscpu | grep -m 1 "Architecture:" | sed 's/[^=:]*[=:] //' | sed 's|[/ ]||g')
	proc_amount=$(nproc)
		
	if [[ -z "$ram_type" ]]; then
		ram_type="VM or no dmidecode"
	fi
	
	if [ $(( ram_amount_mb / 500 )) -le $proc_amount ]; then
		(( threeways = ($ram_amount_mb - 1000) / 384 ))
		(( oneways =  $proc_amount - $threeways  ))
		options="-t $threeways -1 $oneways"
    fi
	
	timeout 300 ./$1 --benchmark $options > out.txt
	sed -i -e '1,7d' out.txt

	hashrate=$(cat out.txt | awk '{ sum += $4 } END { if (NR > 0) print sum / NR }')
	
	echo "Your calculated hashrate is $hashrate"
	
	read -n 100 -p "Would you like to add a comment? If not press Enter otherwise type in your comment and press Enter. (max. 100 chars) " com
	
	comment="Options: $options / Comment: $com"

	rm -rf out.txt strp.txt

	wget -O /dev/null -o /dev/null "http://hashcomp.lls-technik.com/submit?p1=\"$proc\"&p2=$proc_frq&p3=\"$ram_type\"&p4=$ram_amount_mb&p5=$ram_speed&p6=\"$os\"&p7=\"$kernel\"&p8=\"$proc_type\"&p9=$hashrate&p10=\"$comment\""

}

case $type in 
   x86_64) 
		echo "The Benchmark will take about 6 minutes."
		chmod +x cpuminer_x64
		benchmark cpuminer_x64
		echo "Benchmark submitted."
		echo "If you like what I'm doing please donate :) VRM/VRC VJniF5bP9Acy7ce33yR4jRYSQ66Z4vGH8s"
		exit 0;;
       
   armv71)
		echo "The Benchmark will take about 6 minutes."
		chmod +x cpuminer_armv7
		benchmark cpuminer_armv7
		echo "Benchmark submitted."
		echo "If you like what I'm doing please donate :) VRM/VRC VJniF5bP9Acy7ce33yR4jRYSQ66Z4vGH8s"
		exit 0;;
	  
   aarch64)
		echo "The Benchmark will take about 6 minutes."
		chmod +x cpuminer_armv8
		benchmark cpuminer_armv8
		echo "Benchmark submitted."
		echo "If you like what I'm doing please donate :) VRM/VRC VJniF5bP9Acy7ce33yR4jRYSQ66Z4vGH8s"
		exit 0;;
		
  * )   echo "Your CPU Architecture is not supported. Sorry"
		exit 1;;
     
  esac 
done 